workspace(name = "examples")

load(":examples_repositories.bzl", "repositories")

repositories()

load(":examples_deps.bzl", "deps")

deps()

load(":examples_transitive_deps.bzl", "transitive_deps")

transitive_deps()

load("@complex_sys_deps//:defs.bzl", "pinned_rust_install")

pinned_rust_install()
